### Update diary by ID for admin1
PUT http://localhost:8080/admin1/api/v1/diaries/{id}
Content-Type: application/json

{
  "title": "Updated Test Diary for admin1",
  "content": "This is an updated test diary content for admin1"
}

### Update diary by ID for admin2
PUT http://localhost:8080/admin2/api/v1/diaries/{id}
Content-Type: application/json

{
  "title": "Updated Test Diary for admin2",
  "content": "This is an updated test diary content for admin2"
}