### Get diary by ID for admin1
GET http://localhost:8080/admin1/api/v1/diaries/{id}
Accept: application/json

### Get diary by ID for admin2
GET http://localhost:8080/admin2/api/v1/diaries/{id}
Accept: application/json