### Get all diaries for admin1
GET http://localhost:8080/admin1/api/v1/diaries
Accept: application/json

### Get all diaries for admin2
GET http://localhost:8080/admin2/api/v1/diaries
Accept: application/json